class Countries {
  static List<String> countriesList() {
    return <String>[ // https://flagpedia.net/emoji
      ("Afghanistan%🇦🇫"),
      ("Albania%🇦🇱"),
      ("Algeria%🇩🇿"),
      ("Andorra%🇦🇩"),
      ("Angola%🇦🇴"),
      ("Antigua and Barbuda%🇦🇬"),
      ("Argentina%🇦🇷"),
      ("Armenia%🇦🇲"),
      ("Australia%🇦🇺"),
      ("Austria%🇦🇹"),
      ("Azerbaijan%🇦🇿"),
      ("Bahamas%🇧🇸"),
      ("Bahrain%🇧🇭"),
      ("Bangladesh%🇧🇩"),
      ("Barbados%🇧🇧"),
      ("Belarus%🇧🇾"),
      ("Belgium%🇧🇪"),
      ("Belize%🇧🇿"),
      ("Benin%🇧🇯"),
      ("Bhutan%🇧🇹"),
      ("Bolivia%🇧🇴"),
      ("Bosnia and Herzegovina%🇧🇦"),
      ("Botswana%🇧🇼"),
      ("Brazil%🇧🇷"),
      ("Brunei%🇧🇳"),
      ("Bulgaria%🇧🇬"),
      ("Burkina Faso%🇧🇫"),
      ("Burundi%🇧🇮"),
      ("Cambodia%🇰🇭"),
      ("Cameroon%🇨🇲"),
      ("Canada%🇨🇦"),
      ("Cabo Verde%🇨🇻"), // todo Capo ?
      ("Central African Republic%🇨🇫"),
      ("Chad%🇹🇩"),
      ("Chile%🇨🇱"),
      ("China%🇨🇳"),
      ("Colombia%🇨🇴"),
      ("Comoros%🇰🇲"),
      ("Costa Rica%🇨🇷"),
      ("Croatia%🇭🇷"),
      ("Cuba%🇨🇺"),
      ("Curacao%🇨🇼 ------------------"),
      ("Cyprus%🇨🇾"),
      ("Czech Republic%🇨🇿 -------------"), // Czechia ?
      ("Congo%CD -------------------"), // todo flag
      ("Denmark%🇩🇰"),
      ("Djibouti%🇩🇯"),
      ("Dominica%🇩🇲"),
      ("Dominican Republic%🇩🇴"),
      ("Ecuador%🇪🇨"),
      ("Egypt%🇪🇬"),
      ("El Salvador%🇸🇻"),
      ("Equatorial Guinea%🇬🇶"),
      ("Eritrea%🇪🇷"),
      ("Estonia%🇪🇪"),
      ("Eswatini (Swaziland) %🇸🇿"),
      ("Ethiopia%🇪🇹"),
      ("Fiji%🇫🇯"),
      ("Finland%🇫🇮"),
      ("France%🇫🇷"),
      ("Gabon%🇬🇦"),
      ("Gambia%🇬🇲"),
      ("Georgia%🇬🇪"),
      ("Germany%🇩🇪"),
      ("Ghana%🇬🇭"),
      ("Greece%🇬🇷"),
      ("Grenada%🇬🇩"),
      ("Guatemala%🇬🇹"),
      ("Guinea%🇬🇳"),
      ("Guinea-Bissau%🇬🇼 ---------------"),
      ("Guyana%🇬🇾"),
      ("Haiti%🇭🇹"),
      ("Honduras%🇭🇳"),
      ("Hong Kong%🇭🇰------------"),
      ("Hungary%🇭🇺"),
      ("Iceland%🇮🇸"),
      ("India%🇮🇳"),
      ("Indonesia%🇮🇩"),
      ("Iran%🇮🇷"),
      ("Iraq%🇮🇶"),
      ("Ireland%🇮🇪"),
      ("Isle of Man%🇮🇲-----------"),
      ("Israel%🇮🇱"),
      ("Italy%🇮🇹"),
      ("Ivory Coast%CI --------------"),
      ("Jamaica%🇯🇲"),
      ("Japan%🇯🇵"),
      ("Jordan%🇯🇴"),
      ("Kazakhstan%🇰🇿"),
      ("Kenya%🇰🇪"),
      ("Kosovo%🇽🇰"),
      ("Kuwait%🇰🇼"),
      ("Kyrgyzstan%🇰🇬"),
      ("Laos%🇱🇦"),
      ("Latvia%🇱🇻"),
      ("Lebanon%🇱🇧"),
      ("Lesotho%🇱🇸"),
      ("Liberia%🇱🇷"),
      ("Libya%🇱🇾"),
      ("Liechtenstein%🇱🇮"),
      ("Lithuania%🇱🇹"),
      ("Luxembourg%🇱🇺"),
      ("Macau%🇲🇴 ----------------"),
      ("Macedonia%MK-----------------"), //todo flag
      ("Madagascar%🇲🇬"),
      ("Malawi%🇲🇼"),
      ("Malaysia%🇲🇾"),
      ("Maldives%🇲🇻"),
      ("Mali%🇲🇱"),
      ("Malta%🇲🇹"),
      ("Mauritania%🇲🇷"),
      ("Mauritius%🇲🇺"),
      ("Mexico%🇲🇽"),
      ("Moldova%🇲🇩"),
      ("Monaco%🇲🇨"),
      ("Mongolia%🇲🇳"),
      ("Montenegro%🇲🇪"),
      ("Montserrat%🇲🇸 --------------"),
      ("Morocco%🇲🇦"),
      ("Mozambique%🇲🇿"),
      ("Myanmar%🇲🇲------------------"),
      ("Namibia%🇳🇦"),
      ("Nepal%🇳🇵"),
      ("Netherlands%🇳🇱"),
      ("New Zealand%🇳🇿"),
      ("Nicaragua%🇳🇮"),
      ("Niger%🇳🇪"),
      ("Nigeria%🇳🇬"),
      ("North Korea%🇰🇵 ---------------------------------"),
      ("Norway%🇳🇴"),
      ("Oman%🇴🇲"),
      ("Pakistan%🇵🇰"),
      ("Palestine%🇵🇸------------------"),
      ("Panama%🇵🇦"),
      ("Papua New Guinea%🇵🇬"),
      ("Paraguay%🇵🇾"),
      ("Peru%🇵🇪"),
      ("Philippines%🇵🇭"),
      ("Poland%🇵🇱"),
      ("Portugal%🇵🇹"),
      ("Puerto Rico%🇵🇷 ------------"),
      ("Qatar%🇶🇦"),
      ("Republic Congo%🇨🇬 -------------"),
      ("Romania%🇷🇴"),
      ("Russia%🇷🇺"),
      ("Rwanda%🇷🇼"),
      ("San Marino%🇸🇲"),
      ("Saudi Arabia%🇸🇦"),
      ("Senegal%🇸🇳"),
      ("Serbia%🇷🇸"),
      ("Seychelles%🇸🇨"),
      ("Sierra Leone%🇸🇱"),
      ("Singapore%🇸🇬"),
      ("Slovakia%🇸🇰"),
      ("Slovenia%🇸🇮"),
      ("Somalia%🇸🇴"),
      ("South Africa%🇿🇦"),
      ("South Korea%🇰🇷 -----------"),
      ("South Sudan%🇸🇸"),
      ("Spain%🇪🇸"),
      ("Sri Lanka%🇱🇰"),
      ("Sudan%🇸🇩"),
      ("Suriname%🇸🇷"),
      ("Sweden%🇸🇪"),
      ("Switzerland%🇨🇭"),
      ("Syria%🇸🇾"),
      ("Taiwan%🇹🇼-------------"),
      ("Tajikistan%🇹🇯"),
      ("Tanzania%🇹🇿"),
      ("Thailand%🇹🇭"),
      ("Togo%🇹🇬"),
      ("Tunisia%🇹🇳"),
      ("Turkey%🇹🇷"),
      ("Turkmenistan%🇹🇲-------------"),
      ("Uganda%🇺🇬"),
      ("Ukraine%🇺🇦"),
      ("United Arab Emirates%🇦🇪"),
      ("United Kingdom%🇬🇧"),
      ("United States%🇺🇸"),
      ("Uruguay%🇺🇾"),
      ("Uzbekistan%🇺🇿"),
      ("Vanuatu%🇻🇺 -----------"),
      ("Vatican%🇻🇦---------------"),
      ("Venezuela%🇻🇪"),
      ("Vietnam%🇻🇳"),
      ("Western Sahara%🇪🇭"),
      ("Yemen%🇾🇪"),
      ("Zambia%🇿🇲"),
      ("Zimbabwe%🇿🇼")
    ];
  }
}